version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - AccountID=$(aws sts get-caller-identity --query "Account" --output text)
      - ECR_NAME=<ECR Name>
      - aws ecr get-login-password --region ap-northeast-2 | docker login --username AWS --password-stdin $AccountID.dkr.ecr.ap-northeast-2.amazonaws.com
      - ECR_URI=$AccountID.dkr.ecr.ap-northeast-2.amazonaws.com/$ECR_NAME
      - IMAGE_TAG="latest"
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t $ECR_URI:$IMAGE_TAG .
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker images...
      - docker push $ECR_URI:$IMAGE_TAG
      - echo "$(jq .containerDefinitions[].image=\"$ECR_URI:$IMAGE_TAG\" taskdef.json)" > taskdef.json
artifacts:
  files:
    - 'appspec.yaml'
    - 'taskdef.json'